### ISSUE TITLE
`Themes` sub-heading vanishing from the Command Palette 

### ISSUE THREAD

**Issue by anurag-roy** [cristicretu/cretu.dev#182]
<img width="729" alt="Screenshot 2022-05-30 at 1 07 47 AM" src="https://user-images.githubusercontent.com/53750093/170888587-ee43a22c-f265-4eb8-b76b-20999635829c.png">

The `Themes` sub heading vanishes sometimes, and the selection indicator goes out of place (its position is probably getting miscalculated).

Steps to reproduce:
1. Open command palette
2. Type "theme"

**Comment by cristicretu** [comment]
Thanks for the heads up!

The problem was with my logic, using the index of the filtered commands instead of the actual array size.

```diff
- if (i === 0)
+ if (answer.length === 0)
```

**Comment by anurag-roy** [comment]
No worries mate! @cristicretu
